### ISSUE TITLE
This is awsome

### ISSUE THREAD

**Issue by AmirMFarhang** [Kasra-Kamran/Tetrust#1]
Dude, will you continue this? please continue and let me in this project, let me innnnnnnnnnnnnnnnnnnnnnnnnnnnn @Kasra-Kamran

**Comment by Kasra-Kamran** [comment]
of course I will, this project still has a long way to go.

**Comment by AmirMFarhang** [comment]
dont give me that 😑 I said LET ME IN idk if I can send gif here but, references to that one gif

**Comment by Kasra-Kamran** [comment]
sure man, it's a public repo, just learn rust and create a pull request.

**Comment by AmirMFarhang** [comment]
why are u so calm, you made a revolution, you should make a cult out of it like last(kasra+rust got it?), are you a prophet, cause rust is your god
